Vagrant.configure("2") do | config |

    config.vm.define "tacikgozS" do | server |
        server.vm.box = "debian/bullseye64"
        server.vm.hostname = "tacikgozS"
        server.vm.network "private_network", ip: "192.168.56.110"

        server.vm.provider "virtualbox" do |vb|
            vb.name = "tacikgozS"
            vb.memory = "4096"
            vb.cpus = 2
        end
        server.vm.provision "shell", path: "scripts/provision.sh"
    end
end

